const KEY='bolsaathi.contacts.v1';
const $=id=>document.getElementById(id);
let contacts=load(), activeFilter='all';
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(contacts));render()}catch{toast('Browser storage unavailable. Check device storage settings.') }}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'BS'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=$('search').value.trim().toLowerCase();const filtered=contacts.filter(c=>(activeFilter==='all'||c.kind===activeFilter)&&[c.name,c.company,c.email,c.phone,c.notes,c.language,c.kind].some(v=>(v||'').toLowerCase().includes(q)));$('totalCount').textContent=contacts.length;$('clientCount').textContent=contacts.filter(c=>c.kind==='Client').length;$('urduCount').textContent=contacts.filter(c=>c.language==='Urdu'||c.language==='Both').length;$('navCount').textContent=contacts.length;const grid=$('contactGrid');grid.replaceChildren();if(!filtered.length){const empty=document.createElement('div');empty.className='empty';empty.innerHTML=contacts.length?'<strong>No contacts match your search</strong>Try another name or change the filter.':'<strong>Your contact book starts here.</strong>Add a client or collaborator and keep their preferred language and meeting context handy.';grid.append(empty);return}for(const c of filtered){const card=document.createElement('article');card.className='contact-card';card.innerHTML=`<div class="card-head"><div class="avatar">${esc(initials(c.name))}</div><div class="name-wrap"><h2>${esc(c.name)}</h2><p>${esc(c.company||c.kind)}</p></div><span class="lang-pill">${esc(c.language)}</span></div><div class="contact-details">${c.email?`<div class="detail"><span>✉</span><span>${esc(c.email)}</span></div>`:''}${c.phone?`<div class="detail"><span>↗</span><span>${esc(c.phone)}</span></div>`:''}<div class="detail"><span>◈</span><span>${esc(c.kind)}</span></div></div><div class="notes">${esc(c.notes||'No conversation notes yet.')}</div><div class="card-actions"><button class="btn" data-action="edit" data-id="${esc(c.id)}">Edit</button><button class="btn" data-action="copy" data-id="${esc(c.id)}">Copy details</button><button class="btn danger" data-action="delete" data-id="${esc(c.id)}">Delete</button></div>`;grid.append(card)}}
function openModal(c=null){$('contactForm').reset();$('contactId').value=c?.id||'';$('modalTitle').textContent=c?'Edit contact':'Add a contact';$('name').value=c?.name||'';$('company').value=c?.company||'';$('email').value=c?.email||'';$('phone').value=c?.phone||'';$('kind').value=c?.kind||'Client';$('language').value=c?.language||'English';$('notes').value=c?.notes||'';$('formError').textContent='';$('modalBackdrop').classList.add('open');setTimeout(()=>$('name').focus(),30)}
function closeModal(){$('modalBackdrop').classList.remove('open')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function download(filename,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
$('addBtn').addEventListener('click',()=>openModal());$('closeModal').addEventListener('click',closeModal);$('cancelModal').addEventListener('click',closeModal);$('modalBackdrop').addEventListener('click',e=>{if(e.target===$('modalBackdrop'))closeModal()});$('search').addEventListener('input',render);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()}));
$('contactForm').addEventListener('submit',e=>{e.preventDefault();const name=$('name').value.trim();if(!name){$('formError').textContent='Please enter a name.';return}const id=$('contactId').value||crypto.randomUUID();const item={id,name,company:$('company').value.trim(),email:$('email').value.trim(),phone:$('phone').value.trim(),kind:$('kind').value,language:$('language').value,notes:$('notes').value.trim(),updatedAt:new Date().toISOString()};const i=contacts.findIndex(c=>c.id===id);if(i>=0)contacts[i]=item;else contacts.unshift(item);persist();closeModal();toast(i>=0?'Contact updated':'Contact saved on this device')});
$('contactGrid').addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const c=contacts.find(x=>x.id===b.dataset.id);if(!c)return;if(b.dataset.action==='edit')openModal(c);if(b.dataset.action==='delete'){if(confirm(`Delete ${c.name} from this device?`)){contacts=contacts.filter(x=>x.id!==c.id);persist();toast('Contact deleted')}}if(b.dataset.action==='copy'){const txt=[c.name,c.company,c.email,c.phone,`Relationship: ${c.kind}`,`Preferred language: ${c.language}`,`Notes: ${c.notes}`].filter(Boolean).join('\n');try{await navigator.clipboard.writeText(txt);toast('Contact details copied')}catch{download('bolsaathi-contact.txt',txt,'text/plain;charset=utf-8');toast('Clipboard unavailable; downloaded details')}}});
$('exportBtn').addEventListener('click',()=>{if(!contacts.length)return toast('Add a contact before exporting.');const cols=['name','company','email','phone','kind','language','notes'];download('bolsaathi-contacts.csv',[cols.join(','),...contacts.map(c=>cols.map(k=>csvCell(c[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8');toast('Contacts exported as CSV')});
$('importBtn').addEventListener('click',()=>$('csvFile').click());$('csvFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();const rows=text.split(/\r?\n/).filter(Boolean);if(rows.length<2)throw Error('CSV needs a header row and at least one contact.');const parse=line=>{const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&quoted&&line[i+1]==='"'){cur+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};const headers=parse(rows.shift()).map(x=>x.trim().toLowerCase());const imported=rows.map(row=>{const vals=parse(row);const o={};headers.forEach((h,i)=>o[h]=vals[i]||'');if(!o.name?.trim())return null;return{id:crypto.randomUUID(),name:o.name.trim(),company:o.company||'',email:o.email||'',phone:o.phone||'',kind:['Client','Collaborator','Other'].includes(o.kind)?o.kind:'Other',language:['English','Urdu','Both','Other'].includes(o.language)?o.language:'English',notes:o.notes||'',updatedAt:new Date().toISOString()}}).filter(Boolean);if(!imported.length)throw Error('No valid rows with a name were found.');const known=new Set(contacts.map(c=>(c.email||'').toLowerCase()).filter(Boolean));const fresh=imported.filter(c=>!c.email||!known.has(c.email.toLowerCase()));contacts=[...fresh,...contacts].slice(0,500);persist();toast(`Imported ${fresh.length} new contact(s)`)}catch(err){toast(err.message||'Could not import this CSV')}finally{$('csvFile').value=''}});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}});render();
